# Generated by Django 4.0.6 on 2022-07-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='id',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='id',
        ),
        migrations.AlterField(
            model_name='search',
            name='key_word',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watchid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
