# Generated by Django 4.0.6 on 2022-07-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_search_id_remove_watch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('mid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=20, verbose_name=True)),
            ],
        ),
    ]
